### ISSUE TITLE
Animated transitions: research spike

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#124]
Timebox 1d:
 - connection to the lifecycle events
 - impact on performance
 - older browsers support (hi, IE11) - browser APIs / external dependencies
 - impact on the Vaadin.Router API (what new properties / methods are needed)
 - how to test
 - plan the further work

**Comment by web-padawan** [comment]
Prototyping result in the branch: https://github.com/vaadin/vaadin-router/tree/spike/animated-transitions

**Comment by web-padawan** [comment]
## Lifecycle Events
- `__setOutletContent` needs to be changed, and probably split into two methods: a method to remove old content, and a method to insert a new one. The first of those should return a Promise, which resolves once the animation for removed view has been triggered.
- We should consider using lifecycle callbacks for this, so that we could perform some async tasks before removing elements from the DOM

## Impact on the API:
- `animate: true` option added to the route config is the simplest option. This would run animations, if any. 
- The `opening` and `closing` attributes (names TBD) exposed on the view element
- User can apply the animations to the view component using the following CSS:

```css
@keyframes fadeOut {
  0% {
    opacity: 1;
  }

  100% {
    opacity: 0;
  }
}

:host([closing]) {
  animation: 1s fadeOut;
}
```
