### ISSUE TITLE
Image links should not be caught in the router

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-router#142]
Image links should be skipped by the router and processed by browser regularly.

# Code sample
```html
<p><a href="/rick.png">link to an image</a></p>
```

# Expected behaviour
1) Click on link
2) Image is opened in browser normally
3) Get rickrolled

# Actual behaviour
1) Click on link
2) You end up on the 404 page of your app
3) No rickroll.
4) Press browser refresh and then you get to the image.

# Appropriate image for testing purposes.
![rick](https://user-images.githubusercontent.com/525503/40975888-115ef7ac-68d5-11e8-97d8-ff4773a30c91.png)

**Comment by vlukashov** [comment]
Nice and detailed issue description! Thanks!

That's the expected behavior for Vaadin.Router 1.0. If you want to add direct image links into your app we recommend you to use `target="_blank"` so that the app stays open, and the image gets opened in a separate browser window.
```
<p><a href="/rick.png" target="_blank">link to an image</a></p>
```

Or use the `download` attribute so that the image gets downloaded.
```
<p><a href="/rick.png" download>link to an image</a></p>
```

Alternatively, if you really want the image to get opened in the current window (replacing the app), please explicitly define a `/rick.png` route (or a `(.*).png` route) with a custom action that forces the browser to reload the page by `window.location.pathname = context.pathname`.
```
{path: '(.*).png', action: context => { window.location.pathname = context.pathname }},
```
