### ISSUE TITLE
add Vaadin.Router into Expence Manager

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#176]
As a developer using the [Expense Manager](https://github.com/vaadin/expense-manager-demo) starter, I want to have Vaadin.Router in my app by default (along with all other Vaadin Components goodness).

DoD:
 - both Expense Manager Core and Pro starters are updated to use Vaadin.Router
 - the app one gets after following the instructions on https://vaadin.com/start/v10-pwa includes Vaadin.Router
- the app one gets after following the instructions on https://vaadin.com/start/v10-pwa-pro includes Vaadin.Router

**Comment by web-padawan** [comment]
PR up at vaadin/expense-manager-demo#112

**Comment by web-padawan** [comment]
Metrics to measure and report:
- [ ] Lighthouse "Performance" audit, compared to current master
- [ ] total size of the bundled app, compared to current master

**Comment by web-padawan** [comment]
### Total Size

Measured the download size for initial login screen for the bundled app in desktop Chrome 67.
App is built using `polymer-cli` v1.7.7, the preset is `es6-bundled`.

### Before: current master

- 449 KB transferred
- Load: 2.41 s
- Finish: 2.95 s
- expense-app.html: 66.7 KB

![before](https://user-images.githubusercontent.com/10589913/42377256-3b8a9964-812b-11e8-91e0-20f8215ce93e.png)

Note: current master is using `<iron-pages>` and `Polymer.importHref` to load `overview-page.html`
That's why the total size is significantly bigger.

### After: with Vaadin.Router

- 449 KB transferred
- Load: 2.41 s
- Finish: 2.95 s
- expense-app.html: 70.0 KB + login-page.html 3.4 KB

![after](https://user-images.githubusercontent.com/10589913/42377250-367154ea-812b-11e8-8131-c2e14a827afc.png)


Note: proper lazy loading is now implemented, the service worker precaches `overview-page.html` ensuring that navigation to it after the user is logged in is really fast (response is from Service Worker).

**Comment by vlukashov** [comment]
Both the core and pro Expense Manager versions are updated and deployed:
 - Core: https://expensemanager.demo.vaadin.com/ (https://github.com/vaadin/expense-manager-demo/pull/112)
 - Pro: https://expensemanager-pro.demo.vaadin.com/ (https://github.com/vaadin/expense-manager-demo-pro/pull/30)
