### ISSUE TITLE
Get rid of vaadin-usage-statistics

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-router#241]
From https://github.com/Polymer/pwa-starter-kit/pull/195#issuecomment-406645735

> I haven't investigated what vaadin-router exactly does, but I'd prefer a starter kit that does not send any usage statistics (in both development and production mode).

Whoever made the decision to add that dependency to the router please leave a comment with the answer on question "why exactly?", because the related PR doesn't contain any reasoning: https://github.com/vaadin/vaadin-router/pull/235

**Comment by marcushellberg** [comment]
I've been against collecting statistics from the start and I'm pushing the management team to get it dropped. Even if it doesn't send any personalized info, the fact that there's a `usage-statistics` dependency and that my app would ping some 3rd party server just looks bad.

**Comment by abdonrd** [comment]
Totally agree! :)

**Comment by marcushellberg** [comment]
Just to give a bit of context to anyone reading this later on, here's what the statistics gathering does: https://github.com/vaadin/vaadin-usage-statistics/blob/master/README.md. It's not that it's doing anything evil, and it only gets loaded if you are running on localhost and not bundled. 

The issue more the perception of our components if they include this dependency.

**Comment by limonte** [comment]
Good news: `vaadin-usage-statistics` has been removed from the stable version https://github.com/vaadin/vaadin-router/releases/tag/v1.0.0 :tada:

Bad news: there's a possibility it'll be added again in one of future releases.

**Comment by limonte** [comment]
UPD: `vaadin-usage-statistics` will be added to the upcoming minor release `1.1.0`.

⚠️ if you don't want `vaadin-usage-statistics` in your application, change the dependency to semver patch range: `~1.0.0` or `1.0.x`.

**Comment by Legioth** [comment]
Yes, usage statistics collection is reintroduced. Sorry for the confusion caused by poor internal communication leading to removal and then adding it back again.

We understand that collecting statistics in this way is a controversial topic that will upset some developers. The background here is that we want to better understand to what degree our different products are used and how they are used together. Also, we are a commercial company with obligations to both the developer community as well as to our shareholders who ask for insights about how our business is thriving.

We are doing everything we can to make the usage statistics collection as unobtrusive and transparent as possible. For instance, the monthly stats sending trigger has a [95% chance of being a no-op](https://github.com/vaadin/vaadin-usage-statistics/blob/6ec30a1651f02e5612f5541e88ce5360147f4430/vaadin-usage-statistics.js#L313) so that we can only do aggregate statistics but never track any individual developer.

Another example is that we make it as easy as possible to opt out. It was the lack of a good way of opting out for NPM users combined with broken internal communication that made us prematurely remove the usage statistics collection right before releasing 1.0.0. Now that an opt-out alternative [for NPM](https://github.com/vaadin/vaadin-usage-statistics/pull/27/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) is being added, we will release 1.1.0 that makes Vaadin Router consistent with all other Vaadin products.

I would encourage anyone concerned with usage statistics being collected to still upgrade to 1.1.0 and explicitly opt out from the collection of stats since that's the version that further development will be based on.

Kind regards,
Leif Åstrand
CTO, Vaadin

**Comment by Legioth** [comment]
Just a quick update to point out that the 5% sampling that I mentioned in my previous post is being changed to 100% sampling as of https://github.com/vaadin/vaadin-usage-statistics/pull/47.

Other aspects such as the precautions to not affect end-users in production deployments are still the same.

**Comment by dzintars** [comment]
Just leaving my humble feedback.
I totally understand the reasoning, but exactly this one feature is no-go for me personally even for the local dev. I don't even care what statistics you guys are really collecting. The same day i tried this router and saw 3rd party net requests, i just immediately wiped it out. Probably i am too sensitive to this kind stuff... but... at the end it's no-go even for my sandbox projects. And i know some enterprise  policies which does not even allow to bring such dependencies in the repos and some could be even fired. 😄 
While i like many features of this router, this single feature kills it.
