### ISSUE TITLE
Routing within parameterized routes re-creates the component each route change

### ISSUE THREAD

**Issue by LarsDenBakker** [vaadin/vaadin-router#250]
When switching URLs which stay on the same route, the route's component is recreated each time.

The simplest reproduction:

```
  const router = new Router(document.getElementById('outlet'));
  router.setRoutes([
    {path: '(.*)', component: 'my-component'},
  ]);
```

Any URL change will cause `my-component` to be re-instantiated

Similarly:

```
  const router = new Router(document.getElementById('outlet'));
  router.setRoutes([
    {path: '/foo/:bar', component: 'my-component'},
  ]);
```

Switching between the URLs /foo/foo, /foo/bar and /foo/baz will because `my-component` to be re-instantiated thrice.

I am on board with the idea clearing the dom on route changes, but if you're staying on the same route it's wasteful to do that extra work. It also causes any state (API calls, input fields, toggle states) of the components to be lost. 

Also, when switching between two routes which match the same component it might also be a good idea to keep the same component instance.

**Comment by moderndeveloperllc** [comment]
@LarsDenBakker I can see a scenario where this isn't the best idea. If you have a list of users in a nav bar, when you click on the new user, you want the lifecycle calls to hit (`onBeforeEnter()` for example) so you can get new data. The Polymer `app-route` keeps the component in the DOM, and it causes me all sorts of headaches trying to reuse a custom component for add and edit of data.

If they were to consider this request, I would hope that it would be an opt-in functionality.

**Comment by vlukashov** [comment]
The decision to take the route Web Component through all lifecycle events (onBeforeLeave, onAfterLeave, onBeforeEnter, onAfterEnter) was made to support that exact use case which **@⁠moderndeveloperllc** has described.

There is indeed space for optimization. Especially, if your use case would benefit from keeping the same Web Component instance between navigation. If I understand the case correctly, this will be addressed by adding support for view caching (#44).

**Comment by fmipsylone** [comment]
I think it's the best way to keep the behavior like it is today. So to continue re-rendering the same component ever the location changed or not.

This allows a best control of component rendering in applications.
For example, You can keep the default behavior for some light components if your application needs that and at the opposite you can implement a MVP design pattern like [GWT toolkit](http://www.gwtproject.org/articles/mvp-architecture.html) does for heavy components by keeping an instance of the View.

The MVP implemented in GWT add an Activity behavior. This Activity is recreated on each location changed and its role is to take an instance of a View in a factory or by DI and hydrate the View with data (Model/Entities,...). The Activity has a role of Presenter of the View. It manages the data to display on the View and the events emitted by the View too.

MVP allows to decouple entirely the core application features from templates (HTML), a best control of emitted events, a best control of data routing and distribution so a perfect one-directional data binding, and better testing purpose as Activity can be a simple class or mixin instead of a HTMLElement...
So by the way MVP is too perfectly compliant with Redux and RxJS behaviors...

**Comment by haijian-vaadin** [comment]
This was fixed already.

**Comment by sijakret** [comment]
i don't think this is fixed, only changing the search (matching the same route) DOES create a new component instance and mounts it.
What is the recommended solution for the use case this thread was opened for (for instance: sync an input field with a query/search param)?
