### ISSUE TITLE
Problem with cordova

### ISSUE THREAD

**Issue by miladkdz** [vaadin/vaadin-router#276]
I am using vaadin router in a cordova app and I have an annoying problem.

- The router cannot resolve the initial route out of the box. I could get it working in a naive way by this code:

```
setTimeout(() => {
          if (window.location.pathname.indexOf('index.html')) {
            Vaadin.Router.go('/');
          }
        }, 200)
```

**Comment by vlukashov** [comment]
From this short snippet it looks like in a Cordova app the initial location is not `/`, but rather something else. Indeed, when started in the browser with `cordova run browser` the initial pathname for a default cordova project is `/index.html`. When started in iOS emulator, the initial pathname for the same project is `/Users/[username]/Library/Developer/CoreSimulator/Devices/C1D5641C-30B5-44F9-A0FA-0E4C83983BDB/data/Containers/Bundle/Application/1F843053-65A6-420E-B687-E47089D43970/HelloCordova.app/www/index.html`

You might need to configure the app to change location to `/` at startup (e.g. with `window.history.pushState(null, document.title, '/');` in order to use Vaadin Router there.

I am closing this issue now since I do not see it as a Router issue. Please feel free to reopen, or continue the discussion in the closed issue.
