### ISSUE TITLE
The redirects are not registering well

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#324]
Follow this steps in this example:

1. Open [example app](https://superficial-cellar-1.glitch.me).
Now you are at `/` route
2. Click on the `Competition ONE` link.
Now you are at `/competition/one` route
3. Click on the `Competition TWO` link.
Now you are at `/competition/two/2019/final` route
Assume "Competition TWO" just have one matchday, the "final"
4. Click on the back browser button.
⚠️ Now you are at `/` route, instead of `/competition/one` route 🤔 ⚠️

App: https://superficial-cellar-1.glitch.me
Code: https://glitch.com/edit/#!/superficial-cellar-1

**Comment by vlukashov** [comment]
I was able to reproduce the issue with the latest version. From a quick investigation it looks like there are two possible use cases of how the redirect can be used and the current implementation supports one of them at the cost of failing with the other one.

Currently supported use case:
 - External navigation to a redirecting route (see https://github.com/vaadin/vaadin-router/issues/141). In this case it is just fine that Router _eats_ one browser history state (uses `replaceState`).
 - In-app navigation to a redirecting route (this ticket). In this case it's a bug that the router _eats_ a browser history state (it should use `pushState` here).

In order to work in both cases Router needs to be smart enough to distinguish between the two cases and act differently.

**Comment by silvelo** [comment]
I am facing the same problem.

**Comment by abdonrd** [comment]
Hi @vlukashov! Any news about this? Thanks in advance!

**Comment by abdonrd** [comment]
Awesome! Thanks @vlukashov!
