### ISSUE TITLE
dynamic imports for lazy loading, allow other extensions

### ISSUE THREAD

**Issue by lastmjs** [vaadin/vaadin-router#326]
Hi there,

Is the lazy loading using dynamic imports under the hood? It would be nice to allow that. My tools are setup so that I can request files with extensions other than `.js` or `.mjs` from the browser, which is in line with the modules spec, so I would like to be able to request `.ts` files. I see no reason why this shouldn't be possible.

Also, instead of rendering components based on tag names, why not render DOM or a TemplateResult or something, similar to sk-router? Seems more flexible

**Comment by web-padawan** [comment]
Hi, sorry about not being able to answer you earlier.

> is the lazy loading using dynamic imports under the hood? 

The script used for simulating imports can be found in [utils.js](https://github.com/vaadin/vaadin-router/blob/c99fdcc79cf3902019e33e58343f5277b9d71167/src/utils.js#L90). It doesn't use `import()` (although that was our initial plan), as Router has to support IE11. 

Also, we did not use `import()` because of how is implemented in webpack: it explicitly requires you at least part of the passed module URL to be static, and does not work with fully dynamic variables. 

My gut feeling is that using [dimport](https://github.com/lukeed/dimport) could be an option. However, it would result in bigger bundle size so that we would have to make it an opt-in solution anyways. 

Note that you are still able to use `import()` inside the route `action` for better tools compatibility and code splitting, and that's what we recommend you to do.

> instead of rendering components based on tag names, why not render DOM or a TemplateResult 

Vaadin Router is a library for web components, not specific to lit-html / LitElement. We decided not to introduce TemplateResult, although that could be done. Extending a Router could be an option.

Closing as this is not an actual issue. Feel free to add your notes if you are still interested.
