### ISSUE TITLE
Does Vaadin Router support relative links ?

### ISSUE THREAD

**Issue by sipi** [vaadin/vaadin-router#332]
Hi,

I've an application on which I try to use Vaadin-Router, but I've an issue with relative paths in links.
If I'm routed on a page `http://localhost/user/tom`, then I click on a link `<a href='./alice'>alice</a>`, so the resulting location is `http://localhost/alice` instead of `http://localhost/user/alice`.

Is it a known behavior?
Thanks

**Comment by vlukashov** [comment]
Vaadin Router resolves all relative URLs relative to the base URL of the app, not relative to its current location. That is, the behavior described in this ticket is expected.

In single-page apps, when routing happens on the client side, that seems to make more sense as the default option. That allows keeping the source code on average simpler. E.g. a navigation component does not need to know the current location in order to render a list of navigation links. When it's rendered as a part of the `user/tom` page the link to the `users` view is the same as when it's rendered as a part of the `alice` page (`./users`).

In order to make a component that has a link relative to the current location, one would need to  calculate its href dynamically based on the app's base URL, and the current location, e.g. `<a href=${makeRelativeUrl(window.location.pathname, './alice')}>`.
