### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by webfolderio** [vaadin/vaadin-router#333]
The title is pretty much self-explanatory. So are we done?
I mean it still works fine as it is but would be nice to know.

**Comment by vlukashov** [comment]
This project is not dead.

Vaadin Router will be an integral part of the future version of Vaadin framework. However, it has arrived first and has not been getting much attention lately, waiting for the other parts to come together.

Your have a very fair point though. Right now Router has a bunch of open issues and no commits since November 2018. The team has been focusing on other things with the intention to come back to building the future Vaadin–including this router–later this year when the priorities so permit.

As this is a [Vaadin Labs](https://vaadin.com/labs/) project at the moment, we would be happy to hear any feedback you might have related to your experience with Vaadin Router. What works well for you? What is lacking?
