### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#34]
As a developer I want to install the `@vaadin/router` package from npm so that I can use Vaadin.Router in my npm-based front-end projects.

DoD:

* `npm install --save @vaadin/router` works (installs a package)
* the `@vaadin/router` package has an ES module bundle (it works in any browser that supports static ES modules: `<script type="module">`)
* the `@vaadin/router` package has an UMD bundle (it works in the browsers that do not support static ES modules: `<script nomodule>`)
* the UMD module adds its exports into the `global.Vaadin` namespace. If the namespace object does not exist, it is created. If does exist, the exports are appended into the existing object.
* the installed `@vaadin/router` package does not contain unnecessary files (tests, demos, linter configs, etc)

**Comment by vlukashov** [comment]
split into prepare (5) and publish (2)

**Comment by web-padawan** [comment]
Note: the `main` field pointing to the UMD bundle not properly resolved by `polymer-cli` when using the ES module as suggested by the docs:

```js
import {Router} from '@vaadin/router';
```
The following error is thrown:
```
Uncaught SyntaxError: The requested module '../../node_modules/@vaadin/router/dist/vaadin-router.umd.js' does not provide an export named 'Router'
```
This is because `polymer-cli` ignores the `browser` field, which is expected to be used instead of the `main`, as it is when using Webpack.
