### ISSUE TITLE
The vaadin-router-location-changed run before route change?

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#340]
See this example: https://glitch.com/edit/#!/silk-collision-1

In the `index.js` we have:

```javascript
window.addEventListener('vaadin-router-location-changed', event => {
  console.log('right event location', event.detail.location);

  console.log('wrong window location!', window.location.href);

  setTimeout(() => {
    console.log('RIGHT window location!', window.location.href);
  }, 0);
});
```

If you click on `See Sam's profile` link you can see that the `window.location.href` is wrong.
I add another example with the setTimeout to see the right value.

**Comment by vlukashov** [comment]
This is by design. Vaadin Router goes through the following events during a navigation round:

 - the new route is fully resolved (i.e. the chain of matching `route` objects is found)
 - all _onBefore_ callbacks are called in the new and the old route chains
 - the `router.location` is updated
 - **the `vaadin-router-location-changed` event is fired**
 - the `window.location` is updated
 - new content is added to the DOM, and the appearing animation is started (if any)
 - disappearing animation is started on the old content (if any)
 - all _onAfter_ callbacks are called in the new and the old route chains
 - the old content is removed from the DOM

I do understand that this may be confusing, but I cannot classify this as a bug. What order of events would you suggest and why?

**Comment by abdonrd** [comment]
Thank you for this great explanation, @vlukashov!
If it isn't already (maybe I haven't seen it), it should be in the documentation.

**Comment by abdonrd** [comment]
My use case is that when the user changes the page, I update the meta tags.

With:

```javascript
updateMetadata(event) {
  const { route } = event.detail.location;

  updateMetadata({
    title: `${route.title} | ${config.name}`,
    description: route.description,
    url: window.location.href
  });
}

async initializeRouter() {
  window.addEventListener('vaadin-router-location-changed', event => {
    this.updateMetadata(event);
  });

  const router = await import('../router/index');
  const mainElement = this.shadowRoot.querySelector('main');

  router.init(mainElement);
}

firstUpdated() {
  this.initializeRouter();
}
```

It updates to:

```html
<title>About | MyApplication</title>
<meta name="description" content="About page description" />
<meta property="og:title" content="About | MyApplication" />
<meta property="og:description" content="About page description" />
<meta property="og:url" content="http://localhost:8080" />
```

And the problem is that the URL is: `http://localhost:8080`
Instead of: `http://localhost:8080/about`

**Comment by abdonrd** [comment]
@vlukashov any news here? Thanks in advance!

**Comment by manolo** [comment]
Doesn't work if instead of using `url: window.location.href` you take the router location ?

**Comment by vlukashov** [comment]
Targeting to fix this in the next patch release (1.5.1), which should come out in a week or two.

**Comment by abdonrd** [comment]
@manolo I think we haven't the full route in the router location:

<img width="596" alt="Screenshot 2019-10-18 at 18 23 15" src="https://user-images.githubusercontent.com/1007051/67086912-6c122500-f1d4-11e9-9e96-d59fef59ab49.png">

**Comment by abdonrd** [comment]
Awesome! Thanks @vlukashov!
