### ISSUE TITLE
Update path-to-regexp dependency

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#347]
From:

```
    "path-to-regexp": "2.4.0"
```

To:

```
    "path-to-regexp": "3.0.0"
```

**Comment by vlukashov** [comment]
Keeping the dependencies up-to-date is a good thing. It's not on top of the priority list for the Vaadin team right now because there is no pressing concern with this dev-time dependency, but a PR would be welcome.

**Comment by abdonrd** [comment]
Now `path-to-regexp` is exported as ES Modules!

https://github.com/pillarjs/path-to-regexp/releases/tag/v4.0.0

And there is a new v5.

**Comment by abdonrd** [comment]
With ES Modules, we can simplify the Rollup setup.

**Comment by abdonrd** [comment]
I update the #351, but we need to review #411.

**Comment by vlukashov** [comment]
Thanks for the update!

The new `path-to-regexp` version allows for tree shaking which could in theory decrease the bundle size. However, in practice the bundle size (`dist/vaadin-router.min.js.gz`) is slightly increasing with this update (from 7.69KB to 7.82KB). At least with the current build setup.

What's the main reason making this dependency upgrade that would justify the increase in the bundle size?
 - Is there any particular feature in the new `path-to-regexp` version that you want to use?
 - Are there critical security fixes that require us to upgrade?

**Comment by abdonrd** [comment]
When I created this issue, it was simply because I tried to update all the dependencies, and this dependency gave problems.

And right now it was because `path-to-regexp` uses ES Modules.

**Comment by vlukashov** [comment]
From the `path-to-regexp` change log [between v2.4.0 and v5.0.0](https://github.com/pillarjs/path-to-regexp/compare/v2.4.0...v5.0.0) I can see only a few changes that may be relevant to Vaadin Router. Those are [the ES modules build](https://github.com/pillarjs/path-to-regexp/commit/4124c3ce63519582fb0bafb52763058bc286dcd7), and two changes to the route pattern syntax:
 - make some path patterns possible at the expense of a breaking change to some other path patterns (https://github.com/pillarjs/path-to-regexp/issues/206)
 - allow nesting non-capturing groups (like `/:foo(\\d+(?:\\.\\d+)?)`) (https://github.com/pillarjs/path-to-regexp/commit/1327699b5c946c262134bdff9af924b09199a9f8)

The 2 changes to the route pattern syntax and the internal library changes alone do not look like a good reason to up the dependency version (taking into account a breaking change, and an increase in the bundle size).

However, the ES module distribution indeed looks like a good reason to upgrade. It allows Vaadin Router to stop bundling this dependency in for its own ES module distribution. That would allow users of Vaadin Router to use `path-to-regexp` directly (instead of using it through the bundled `Vaadin.pathToRegexp` reference).

This would be a breaking to change, so we are talking about a new major. These are the changes I'd like to see related to upgrading `path-to-regexp` and releasing a new major:
 - the ES module build of Vaadin Router does not include the `path-to-regexp` library at all
 - support for IE11 and the UMD bundle build are dropped (the SauceLabs tests should be updated accordingly)
 - the bundle size calculation is updated to take into account the cumulative total of Vaadin Router and path-to-regexp
 - there is a release note explaining the change in the route pattern syntax
    - example of what did not work before but works now
    - example of what used to work before but would not work in the new version without changes
    - how to change the route definitions so that they keep working
 - the own unit tests of Vaadin Router are updated to reflect the change in the route pattern syntax

**Comment by abdonrd** [comment]
Thanks for all the research, @vlukashov! Makes sense for me!

**Comment by abdonrd** [comment]
Another new big-version!

https://github.com/pillarjs/path-to-regexp/releases/tag/v6.0.0
