### ISSUE TITLE
Synchronizing lifecycle callbacks with app states

### ISSUE THREAD

**Issue by lpellegr** [vaadin/vaadin-router#403]
I am wondering how you manage to link Vaadin router lifecycle callbacks with app states in real-world apps.

For instance, the _onBeforeEnter_ callback looks like the perfect place to check if a user has access to a component page and perform a redirection in case it is not allowed to access the page. 

The problem is that when the _onBeforeEnter_ callback is called, you might not have yet the required information to know whether a redirection must be performed. For instance, if the app states are managed with redux, the information will come asynchronously.

How are you doing to synchronize both? meaning waiting in _onBeforeEnter_ for your app state to take a decision about what to do? using a busy-wait loop checking the redux state looks like a bad idea.

Currently, I am checking states in the redux callback and performing redirection with `Router.go(...)` when required (thus making Vaadin router lifecycle callbacks useless). The problem is that the component page is loaded and displayed before the redirection is completed which makes transitions jerky. In that case, a `Router.go(...)` that returns a promise we can await could help but leveraging lifecycle callbacks looks even better.

The current flow on a new page is as follow:

1. Display a loading component page.
2. Wait for the app state to be ready.
3. Decide to redirect or display page component (i.e. replacing/hiding loading component).

If a redirect is performed the page component must not be displayed at all.

Looking forward to reading your experience and thoughts.

**Comment by vlukashov** [comment]
That's a good question. Lifecycle callbacks are surely meant to work nicely with the app state management so that there is no need to create workarounds.

The onBefore callbacks can be async, so it's possible to wait until the state is loaded async and decide to issue a redirect then. Here is a demo: https://glitch.com/edit/#!/403-async-redirect-from-onbeforeenter?path=views/profile-view.js:4:32

The downside is that while waiting for callback resolution the router would display a blank page without any visual indication that something is happening.

If you want to render a 'loading' screen, then you probably should go with the approach that you have now. Rendering  a 'placeholder' component and redirecting `Router.go()` to a different component after the state loads.

**Comment by vlukashov** [comment]
I am closing this issue since it is not a specific bug or a feature request, but I am happy to continue the discussion in the comments.
