### ISSUE TITLE
Generate URL for a route (with parameters)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#45]
As a developer I want to generate URLs that link to other routes of my app, so that when I define a component template I do not have to hard-code the URLs in that template. That is, instead of defining a template like
```
<nav>
  <a href="/myapp/users/">All Users</a>
  <a href="/myapp/users/42">Your profile</a>
<nav>
```
I would define it like
```
<nav>
  <a href="${Router.linkTo({path: '/users'})}">All Users</a>
  <a href="${Router.linkTo({path: '/users/:userid', params: {userid: 42}})}">Your profile</a>
<nav>
```

DoD:
 - there is a public static `linkTo(route)` method on the `Vaadin.Router` class. It accepts a route descriptor with the following properties:
   - `path`: a string, same as any other route path (e.g. `/users/:userid`)
   - `params`: a map where keys are route parameter names and / or indices, and values are parameter values (the same structure as the `params` property of a `location` object)
   - [after [named route support is implemented](https://github.com/vaadin/vaadin-router/issues/255)] `name`: a string, name of a named route. Either `name` or `path` should be provided. If both a provided, `name` is ignored and a warning is triggered.
 - there are docs describing the new API method
 - there is a demo showing how to use the new API method

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

**Comment by vlukashov** [comment]
see #255

**Comment by Legioth** [comment]
Seems to me like `Router.linkTo({path: '/users/:userid', params: {userid: 42}})` is a really verbose way of saying `"/myapp/users/42"`.

Typing out something like `path: '/users/:userid'` completely defeats the purpose. Extracting the `/users/:userid` string to a shared constant helps slightly in simple cases, but not with child routes since you'd then have to maintain the same relationship both in the router config and in the place where you build the path constant values.

Named routes is one practical approach, even though it is also somewhat boilerplatey and has the risk of accidental name collisions in any larger application. To use a named route, `linkTo` should really be an instance method on a specific router instance and not a static method. Otherwise, things would get even more messy with nested routers as described in https://github.com/vaadin/vaadin-router/issues/51.

An alternative approach would be to allow using the same object that was used for configuration as a key to identify the route. Based on the originally suggested API, the concept would look like this:
```
const profileRoute = {path: '/:userId', component: 'x-user-profile'};

router.setRoutes([
  {path: '/users', children: [profileRoute, <more children here>]},
  <more routes here>
]);

let href = router.linkTo({route: profileRoute, params: {userid: 42}});
```

Another source of verbosity with the suggested API is the way it takes only one object parameter with named properties for the different actual parameters. It seems like any anticipated usage is based on a couple of different options to identify the route and another optional property to define the parameters. What about changing the format to `linkTo(routeIdentifier, optionalParams)` with support for these different route identifier types:
* A string starting with `/` is used as a path
* Any other string is used as a named route identifier
* An object is used as a key based on instances passed to `setRoutes`.

If we ever need to add support for some new identification scheme that cannot be distinguished form the current schemes only based on the type, then we can deprecate this method and introduce a new variant with a more verbose API at that point.

The original example could then be simplified to `router.linkTo('/users/:userid', {userid: 42})` or preferably `router.linkTo(profileRoute, {userid: 42})` to avoid the magic string.

The last piece of boilerplate that I'd suggest is to get rid of defining the name of the parameter. If I understood correctly, it was suggested that `params` keys could also be indices, which in this case means that `{userId: 42}` could also be expressed as `{0: 42}` and assumingly then also as `[42]`. I'd suggest taking this one step further to use a rest parameter to allow the ultimate shorthand form: `router.linkTo(profileRoute, 42)`. This would cause some ambiguity with the form `router.linkTo(route, {foo: 42, bar: -42})` since it's not clear whether this defines two named numeric parameters or one parameter with an object value. To resolve this, I'd suggest that we require the user to call `router.linkTo(route, {foo: 42, bar: -42}, undefined)` if they want to make it explicit that the first parameter should be used as an object instead of a map of named parameters.

Finally, I'm not convinced about the name of the function. `linkTo` implies that it would create a link, i.e. an `<a>` element, and not only a URL string. What about `urlTo`, `pathTo` or `hrefTo` instead? Could also consider using `of` as a prefix instead of `to`, e.g. `urlOf`.

**Comment by platosha** [comment]
I think, we can require that in the shorthand form `router.linkTo(route, 42)` all the params must be primitive values. This is a fine limitation, I think, given that they are going to be serialised as strings in the path anyway. That would resolve the ambiguity without any special additional arguments.

I generally agree with these concerns. Some remaining questions though:

1. If `linkTo` is not static, this requires developers to propagate the `router` instance to the view components somehow. Do we have to share the router instance with the component automatically somehow? Generally, developers could propagate the router themselves using a global var, a module, or something, this is a boilerplate too though, so might be inconvenient.
2. Speaking about using the same route object in the router configuration and in the component to generate links from, a similar sharing question arises, especially if the router configuration and the view component are in separate files. Several patterns could be used there to share the routes, (router config export → component import, component export → router config import, having copies all-over-the-place, or everything in the same scope). Is there a preferable pattern to use in the examples?
3. Given that `linkTo` is an instance method, but `go` is still a static method, it would require accessing both a global method and an instance method to make a `go` call to a generated link from a component. Is that an acceptable requirement?

Speaking of naming, I am really used to [the RubyOnRails’ `link_to` helper method](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to). `pathTo` feels like the most confusing name, since `path` could also be used as an argument of this method, plus what we usually call a `path` in the router could be a pattern, e. g., `/user/:userid`, while the string url part is called `pathname`. I would like to admit, it is rare, but a generated link could be potentially used not only in  `<a href="">`, but also as a `<form action="">` value, `go()` argument, a redirect argument, and so on.

**Comment by platosha** [comment]
I must admit, the Rails’ `link_to` is a different thing, it returns a full HTML link `<a href="/thing">Thing</a>`. The href attribute is `url_for`.

Maybe something like this would be nicer to read: `<a href="${urlFor('users', currentUser.id)}"><img src="${urlFor('users', currentUser.id, 'photo', 'small')">My profile</a>`
