### ISSUE TITLE
Can I use it with Angular elements

### ISSUE THREAD

**Issue by secabhi** [vaadin/vaadin-router#461]
Hi As we know angular routing doesn't work with angular elements. Can we use vaadin-router for angular elements? Any example will help

**Comment by vlukashov** [comment]
Yes!

Since Angular Elements let you export Angular components as standard Web Components, there is no reason why they won't work with Vaadin Router. You could use Angular Components both as parent layouts (requires Shadow DOM) and as nested children components. I've created a small demo to show that it's possible: https://stackblitz.com/edit/vaadin-router-with-angular-elements
