### ISSUE TITLE
Slot does not work in case when it is without shadowdom

### ISSUE THREAD

**Issue by victor-shelepen** [vaadin/vaadin-router#571]
I've implemented your tutorial. It works well. Now I am theming using a CSS framework. I understand that I need to rid of Shadow Dom. I did it. Styles were applied. But slot functionality disappeared. Yes, it is mentioned in the documentation. But I do not know how to modify your sample to make it workable. I've looked over the documentation. I see nothing. I understand that your library does satisfy my needs.
Does exist another way?

**Comment by vlukashov** [comment]
This router library is designed to use shadow DOM and slots for rendering nested routes inside parent layouts. At least for layout components there is no way around using shadow DOM. For child view components, however, you are free to disable shadow DOM and use the regular light DOM instead – that works.

There is a way to import styles from a CSS framework inside a shadow root. Instead of including them globally into a page (`<link rel="stylesheet" href="./framework-styles.css">` in the `<head>`), import them into the layout component's styles:
```ts
// use `raw-loader` to get a string or `lit-css-loader` to get a LitElement-specific css literal
import styles from 'framework/styles.css';

@customElement('my-layout')
export class MyLayout extends LitElement {
  static styles = [styles]
  render() {
    return html`
      <p class="fw-bold">such style. very win</p>
      <slot></slot>`;
  }
}
```

I'm closing this issue since it's a question rather than a report that something is broken. But feel free to continue the discussion if you have further questions.
