### ISSUE TITLE
When defining properties for route objects, I need to understand in which order they are executed

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/vaadin-router#94]
List of route properties: 
* redirect
* action
* component
* bundle
* path

Currently there is no documentation on which order of execution will take place for different properties specified.
Also, the router code treats properties differently: it does not allow to specify both `action` and `component` but does allow `redirect` and `action` even though they won't be executed both.

We need to straighten this out, add docs and tests.

**Comment by SomeoneToIgnore** [comment]
path property is not really considered in the order, because it is processed separately and always first, in order to determine which route to use.

The other properties' evaluation order might be the following: 

* bundle
* action (if action returns something, ignore the rest and process its result)
* redirect
* component (i.e. render the page)

Main ideas that lead to this order are:
* component should be the last one: it's considered as a fallback if nothing else had worked. Since redirect and component mutually exclude each other, we might additionally either throw an exception when both are specified or reconsider the API and replace both with destination property or similar
* action always should be before redirect because otherwise it would be impossible to cover use cases like "gather statistics on redirect links visits"

Considering those assumptions, the only three possible orders left are: 
* the proposed one

or

* action
* bundle
* redirect
* component

or 

* action
* redirect
* bundle
* component

Both alternatives can have a case where specified bundle won't be loaded.
In my opinion, if a user explicitly specified some property, it's better to evaluate it, that's why the proposed order is more preferable.
Additionally, the proposed order allows users to validate if bundles have loaded without any errors.

**Comment by web-padawan** [comment]
To me it looks like the redirect should come before the bundle. As a developer, I don't suppose that I have to wait for loading something in case I will be redirected after all. 

It would be nice to have `console.warn` in case if we have both `redirect` and `component`, or `redirect` and `bundle` present at the same time.

**Comment by SomeoneToIgnore** [comment]
I've thought about this also and wondered on why would you specify both `redirect` and `bundle` for the same route if you don't want to have anything loaded before the redirect? :)
The only situation I can think of is:

```
{
  path: '/users', bundle: test.js,
  children: [
    {path: '/u/:user', redirect: '/user/:user'},
    {path: '/user/:user', component: 'x-user-profile'}
  ]
},
```

but even in this case I think it's better to be explicit than implicit and ask users to disable bundle loading with `bundle: null` for the redirect route.

As for the `console.warn`, it's a nice idea.

**Comment by vlukashov** [comment]
**Scenario 1: redirect**
```
router.setRoutes([
  {path: '/u/:user', redirect: '/user/:user'},
  {path: '/user/:user', component: 'x-user-profile'},
]);
```
Why would someone needs to combine a redirect with something else? I'd suggest to document what happens if one does so, but not to optimize for this case.

**Scenario 2: collect stats on redirects**
```
router.setRoutes([
  {path: '/', action: async(context) => {
    var result = await context.next();
    if (result.route.redirectFrom) {
      recordRedirect({
        from: result.route.redirectFrom,
        to: result.route.pathname
      });
    }
  }},
  {path: '/',
    children: [
      {path: '/', component: 'x-home-view'},
      {path: '/u/:user', redirect: '/user/:user'},
      {path: '/user/:user', component: 'x-user-profile'},
    ]
  },
]);
```
The redirect stats would probably be collected on all routes or on a sub-tree of routes, rarely just on one single route.


**Scenario 3: redirect inside a bundle**
```
router.setRoutes([
  {
    path: '/users', bundle: 'users-bundle.js',
    children: [
      {path: '/:user', redirect: '/u/:user'},
    ]
  },
]);
```
Such cases look like a routes config issue: the router would load the bundle only to discover that it needs to redirect to anther route. The best would be to skip bundle loading in this case (but I do not see how to implement that in practice since at the time when the parent route with the `bundle` property is resolved, the router does no know yet that the child route would redirect). At least, we should warn the developer (with a `console.warn()` or throw an `Error` when this happens, or better when such routes config is defined). If this adds too much to the bundle size, we might consider providing different dev and production bundles where safety checks are excluded from the production bundle.

---
My suggestion for the order is:
 - action
 - redirect
 - bundle
 - component

OK combinations:
 - action, redirect
 - action, bundle
 - action, component
 - action, bundle, component
 - bundle, component

NOT OK combinations (should trigger a warning):
 - redirect, bundle
 - redirect, component
 - redirect, bundle, component

**Comment by SomeoneToIgnore** [comment]
Ok, 3 different opinions.
Should we discuss it and come to some consensus or wait for DX test and get user opinions?

**Comment by web-padawan** [comment]
Discussed in person. Agreed on the following order from the proposition above:

- action
- redirect
- bundle
- component
